### ISSUE TITLE
Invalid Access Token on starter project.

### ISSUE THREAD

**Issue by unalCe** [twilio/voice-quickstart-ios#310] opened 2020-02-19 07:58 UTC
### Description

Hello, I'm basically following the Swift tutorial on this page:  https://www.twilio.com/docs/voice/voip-sdk/ios/get-started
I'm trying to achieve the call and hear congratulatory message after step 6. 
But the problem is I'm getting "ERROR:Twilio:[Platform]:Failed to send request, status code: 403" errors when making a call. 

I'm able to make a successful call, in Twilio console using the request URL I got from the Python server by using /makeCall endpoint. I was also able to make a successful call 3 weeks ago, before I updated the TwilioVersion.

Detailed info below.

Thanks in advance. 
#### Code

I'm using voice-quickstart-ios demo on Swift version. The only thing I changed was "baseURLString" which I got from python.server. 

#### Expected Behavior

Call happens with no error, hearing congratulatory message.

#### Actual Behavior

Errors occur in the log. No call happens.

#### Logs

2020-02-19 10:54:22.236898+0300 SwiftVoiceQuickstart[10917:238942] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600003dddcc0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2020-02-19 10:54:22.285361+0300 SwiftVoiceQuickstart[10917:238942] Twilio Voice Version: 5.1.1
2020-02-19 10:54:22.365097+0300 SwiftVoiceQuickstart[10917:238942] providerDidBegin
2020-02-19 10:54:23.703583+0300 SwiftVoiceQuickstart[10917:239065] StartCallAction transaction request successful
2020-02-19 10:54:23.707307+0300 SwiftVoiceQuickstart[10917:238942] provider:performStartCallAction:
2020-02-19 10:54:26.544972+0300 SwiftVoiceQuickstart[10917:238942] provider:didActivateAudioSession:
2020-02-19 10:54:27.143733+0300 SwiftVoiceQuickstart[10917:239065] ERROR:Twilio:[Platform](0x700006535000): Failed to send request, status code: 403
2020-02-19 10:54:27.153245+0300 SwiftVoiceQuickstart[10917:239063] ERROR:Twilio:[Platform](0x70000642f000): Failed to send request, status code: 403
2020-02-19 10:54:27.156021+0300 SwiftVoiceQuickstart[10917:239062] ERROR:Twilio:[Platform](0x7000063ac000): Failed to send request, status code: 403
2020-02-19 10:54:27.281485+0300 SwiftVoiceQuickstart[10917:239063] ERROR:Twilio:[Platform](0x70000642f000): Failed to send request, status code: 403
2020-02-19 10:54:27.283998+0300 SwiftVoiceQuickstart[10917:239063] ERROR:Twilio:[Platform](0x70000642f000): Failed to send request, status code: 403
2020-02-19 10:54:27.287347+0300 SwiftVoiceQuickstart[10917:239063] ERROR:Twilio:[Platform](0x70000642f000): Failed to send request, status code: 403
2020-02-19 10:54:27.293238+0300 SwiftVoiceQuickstart[10917:239065] ERROR:Twilio:[Platform](0x700006535000): Failed to send request, status code: 403
2020-02-19 10:54:27.293647+0300 SwiftVoiceQuickstart[10917:239065] ERROR:Twilio:[Platform](0x700006535000): Failed to send request, status code: 403
2020-02-19 10:54:27.294341+0300 SwiftVoiceQuickstart[10917:239065] ERROR:Twilio:[Platform](0x700006535000): Failed to send request, status code: 403
2020-02-19 10:54:28.008940+0300 SwiftVoiceQuickstart[10917:238942] Call failed to connect: Invalid Access Token issuer/subject
2020-02-19 10:54:28.012200+0300 SwiftVoiceQuickstart[10917:239068] EndCallAction transaction request successful
2020-02-19 10:54:28.015699+0300 SwiftVoiceQuickstart[10917:238942] provider:performEndCallAction:
2020-02-19 10:54:28.017687+0300 SwiftVoiceQuickstart[10917:238942] Unknown UUID to perform end-call action with
2020-02-19 10:54:28.060975+0300 SwiftVoiceQuickstart[10917:238942] provider:didDeactivateAudioSession:

#### Voice iOS SDK

TwilioVoice SDK 5.1.1

#### Xcode

Version 11.2.1 (11B500)

#### iOS Version

13.3.2 

#### iOS Device

iPhone11 Simulator

**Comment by bchen-twilio** [comment] 2020-02-19 18:28
Hi @unalCe 

Just want to confirm - are you still able to make call and connect, but just seeing the `ERROR:Twilio:[Platform]:Failed to send request, status code: 403` message in the debug console? or are you not able to make calls after updating the SDK to 5.1.1?

**Comment by unalCe** [comment] 2020-02-20 12:29
Hi @bchen-twilio

No, I wasn't able to make a call. I did a few successful calls using prior versions of the SDK(can't actually remember, probably it was below 4.0) just by following the tutorial. But now I can't with the new demo project. 
I also want to confirm - Does being able to make successful calls with /makeCall endpoint in TwiML App in Twilio console means everything is working correct on the server side? If so, there is something wrong with the demo I guess. Because all I do is just replace the placeholder of baseURLString with my ngrok public URL.

Thanks for your fast reply.

**Comment by bchen-twilio** [comment] 2020-02-20 18:49
Hi @unalCe 

Thanks for the update.
Majority of the changes that you will need to do to migrate to using 5.1.1 are around the incoming part, so your outgoing capability should not be affected. From the log it seems like the credentials in your access token might be incorrect, therefore you were seeing the error messages. Could it be that some of the account credentials have been updated?

If you keep experiencing this issue, please provide Twilio Call SIDs so we can have a deeper look.

Sorry for the inconvenience.

-bobie

**Comment by piyushtank** [comment] 2020-03-11 01:08
@unalCe Closing the ticket assuming the problem is resolved at your end. Feel to reopen the ticket if you are still running into the issue or have questions.

**Closed by piyushtank** 2020-03-11 01:08 UTC
