### ISSUE TITLE
Crashed: MediaFactoryImpl::signaling 0x0x281934900

### ISSUE THREAD

**Issue by antleung** [twilio/voice-quickstart-ios#487] opened 2021-11-19 20:39 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

We are getting crash from firebase crashlytics

### Steps to Reproduce

Unable to reproduce so far

#### Twilio Call SID(s)

Call SID
CAc4cdebdef4c52a5278113530a7bc5c91

#### Logs
Crashed: MediaFactoryImpl::signaling 0x0x281934900
0  TwilioVoice                    0x3ede84 std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, resip::Handled*>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, resip::Handled*>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, resip::Handled*>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, resip::Handled*> > >::remove(std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, resip::Handled*>, void*>*>) + 4
1  TwilioVoice                    0x3ed5f4 resip::HandleManager::remove(unsigned long) + 244
2  TwilioVoice                    0x3ee024 resip::Handled::~Handled() + 44
3  TwilioVoice                    0x46dc68 twilio::voice::SipCall::~SipCall() + 12
4  TwilioVoice                    0x3d7064 resip::DialogSet::~DialogSet() + 504
5  TwilioVoice                    0x3d738c resip::DialogSet::~DialogSet() + 12
6  TwilioVoice                    0x3dfa70 resip::DialogUsageManager::~DialogUsageManager() + 232
7  TwilioVoice                    0x3dfe68 resip::DialogUsageManager::~DialogUsageManager() + 12
8  TwilioVoice                    0x476048 twilio::voice::SipClient::~SipClient() + 912
9  TwilioVoice                    0x47611c twilio::voice::SipClient::~SipClient() + 12
10 TwilioVoice                    0x46c98c twilio::voice::SignalingClient::~SignalingClient() + 184
11 TwilioVoice                    0x46c9fc twilio::voice::SignalingClient::~SignalingClient() + 12
12 TwilioVoice                    0x11dcc4 webrtc::webrtc_new_closure_impl::ClosureTask<rtc::Thread::Send(rtc::Location const&, rtc::MessageHandler*, unsigned int, rtc::MessageData*)::$_0>::Run() + 28
13 TwilioVoice                    0x11cfac rtc::Thread::QueuedTaskHandler::OnMessage(rtc::Message*) + 48
14 TwilioVoice                    0x11c800 rtc::Thread::Dispatch(rtc::Message*) + 136
15 TwilioVoice                    0x11b7a0 rtc::Thread::ProcessMessages(int) + 168
16 TwilioVoice                    0x11cbe8 rtc::Thread::PreRun(void*) + 60
17 libsystem_pthread.dylib        0x1bfc _pthread_start + 320
18 libsystem_pthread.dylib        0xa758 thread_start + 8

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

6.3.0

#### Xcode

Xcode 13

#### iOS Version

iOS14+

#### iOS Device

All models.

**Comment by dipankadas** [comment] 2024-02-29 17:02
We could not reproduce so far and we don't see it happening in our test suit. Closing it for now. Please feel free to open a new issue if this happens again.

**Closed by dipankadas** 2024-02-29 17:02 UTC
