### ISSUE TITLE
Redirect to accepted call screen from app delegate when user accept the call

### ISSUE THREAD

**Issue by kahantle** [twilio/voice-quickstart-ios#293] opened 2020-01-02 10:08 UTC
pod version 5.1.1

xCode version 11.3

iOS version 13.3

I am making client to client voice call feature in my app. There is Outgoing and accepted call screens.

Now I implemented pkpushkit and other methods in app delegate. When incoming call received, performVoiceCall method is not called in app delegate.

I want to redirect app to accepted call screen from app delegate when user accepts incoming call. 

How can I implement this in swift? Also how and where I have to implement answerOnBridge in node.js as callDidConnect method calls before call answered?

Please help as soon as possible as I am stuck here from many days.

Thanks.

**Comment by piyushtank** [comment] 2020-01-08 18:24
Hi @kahantle 

I recommend using Quickstart code as guidance to resolve the issue. For outgoing calls, when `func provider(_ provider: CXProvider, perform action: CXStartCallAction)` is called by CallKit, you should invoke `performVoiceCall`. See [this](https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceQuickstart/ViewController.swift#L526) example.  In order to receive the `func provider(_ provider: CXProvider, perform action: CXStartCallAction)` back from CallKit, your app should request a `CXStartCallAction`. See [this](https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceQuickstart/ViewController.swift#L592) code for example.

You can set the answerOnBridge flag on ConnectOptions while making an outbound call. If answerOnBridge is set to true, the call should not get connected until the remote participant answers it.

Let me know if you have any questions.

Best,
Piyush

**Comment by piyushtank** [comment] 2020-03-11 01:01
@kahantle  Closing the ticket assuming the problem is resolved at your end. Feel to reopen the ticket if you are still running into the issue or have questions.

**Closed by piyushtank** 2020-03-11 01:01 UTC
Labels: question
