### ISSUE TITLE
Code=31302 "Unsupported Cancel Message Error"

### ISSUE THREAD

**Issue by ream88** [twilio/voice-quickstart-ios#263] opened 2019-09-23 15:56 UTC
### Description

We're receiving a lot of errors like these in our Sentry account:

> Error Domain=com.twilio.voice.error Code=31302 "Unsupported Cancel Message Error" UserInfo={NSLocalizedDescription=Unsupported Cancel Message Error, NSLocalizedFailureReason=This version of the SDK no longer supports processing cancel push notification messages. You must register via `[TwilioVoice registerWithAccessToken:deviceToken:completion:]` with this version of the SDK to stop receiving cancel push notification messages. Cancellations are now handled internally and reported to you on behalf of the SDK.}

The [official migration guide](https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md#migrating-from-twilio-voice-20-to-21) says the following: 

> You must register via [TwilioVoice registerWithAccessToken:deviceToken:completion:] when your App starts.

 However there is no explanation on how to obtain this device token on app start, [neither the example implements](https://github.com/twilio/voice-quickstart-swift/search?q=withAccessToken&unscoped_q=withAccessToken) this requested changes. Am I missing something? What is the best way to fix the issue reported?

### Steps to Reproduce

1. Ship app with Twilio Voice SDK 2.1.0 on iOS 13

**Comment by bchen-twilio** [comment] 2019-09-23 17:34
Hi @ream88 

With the newly introduced PushKit policy in iOS 13, Twilio will no longer send VoIP push notifications for call cancellations. Applications using the Twilio Voice iOS SDK 2.1.0 or 5.0.0 must use the `[TwilioVoice registerWithAccessToken:deviceToken:completion:]` method to subscribe to only the "call" message.

The `deviceToken` is obtained by [initializing the PkPushRegistry](https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceQuickstart/ViewController.swift#L48) and [in the delegate method](https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceQuickstart/ViewController.swift#L214) you will receive the device token and then provide in the `.register()` method.

Hope this helps.

Thanks,
-bobie

**Comment by ream88** [comment] 2019-09-27 14:16
We just shipped a new version and this error still exists. 😞

**Comment by bchen-twilio** [comment] 2019-09-27 18:16
Hi @ream88 

Did the error happen on the mobile client that has called the `TwilioVoice.register()` method when the app was launched? In case where the app is updated but never launched in order for the `register()` method to be executed, the app will still receive the call cancellation notification and receive this error from the SDK.

To workaround (in case calling `TwilioVoice.register()` is not in the path of app launch) and avoid app being terminated on iOS 13, upon receiving this error you can report a dummy incoming call to CallKit with `nil` UUID:

```
- (void)notificationError:(NSError *)error {
    // TVOErrorUnsupportedCancelMessageError received
    CXHandle *callHandle = [[CXHandle alloc] initWithType:CXHandleTypeGeneric value:@"alice"];

    CXCallUpdate *callUpdate = [[CXCallUpdate alloc] init];
    callUpdate.remoteHandle = callHandle;
    callUpdate.supportsDTMF = YES;
    callUpdate.supportsHolding = YES;
    callUpdate.supportsGrouping = NO;
    callUpdate.supportsUngrouping = NO;
    callUpdate.hasVideo = NO;

    [self.callKitProvider reportNewIncomingCallWithUUID:nil update:callUpdate completion:^(NSError *error) {
        // Completion handling
    }];
}
```

-bobie

**Comment by ream88** [comment] 2019-10-01 08:59
@bchen-twilio do you know when these cancel notifications are pushed?

After a lot of debugging and discussion with my team I believe they are only pushed to the app when already in a call. Therefore iOS 13 should not have a problem with them and block my app after a few cancel push notifications.

**Comment by bchen-twilio** [comment] 2019-10-01 18:44
Hi @ream88 

Applications using the Voice 2.1.0/5.0.0 iOS SDK must use the `TwilioVoice.register()` method to register to only the "call" notifications. The "cancel" notification will be delivered regardless the callee's action (accept/reject/ignore) if the registration is not updated. During our investigation we did notice that after a couple of times of not reporting the VoIP notifications to CallKit, iOS started dropping the push notifications without passing them to the application. This happened easily when the app was not in the foreground.

To ensure the incoming capability is not affected, please call the `.register()` method when the app is launched.

Thanks,
-bobie

**Comment by bchen-twilio** [comment] 2019-10-01 20:21
Hi @ream88 

We have also added sample code snippets to our migration guide both for showing how to register when the app is launched and the workaround if the app is still getting the cancel notifications (if registration is not updated). Please check this out: https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md#migrating-from-twilio-voice-20-to-21

Thanks,
-bobie

**Comment by piyushtank** [comment] 2020-03-11 00:41
@ream88 Hoping the issue is resolved. Closing the ticket as it is opened for long. Feel free to reopen if you run into the issue or have questions.

**Closed by piyushtank** 2020-03-11 00:41 UTC
Labels: help wanted
