### ISSUE TITLE
Calls are not being received when the app is in the quit state consistently on IOS 14.

### ISSUE THREAD

**Issue by salman-pixarsart** [twilio/voice-quickstart-ios#427] opened 2021-01-06 06:53 UTC
Description
I have a react-native application that uses a React-Native Plugin (react-native-twilio-programmable-voice) to handle Twilio communication.
Calls are being received in Foreground and Background mode but nothing happens when a call comes when the app is in the quit state.

Steps to Reproduce
Launch the application on the iPhone with iOS 14.x and log in. Make sure Twilio is registered
Kill the app.
Call the phone.

Expected Behavior
That I receive a call

Actual Behavior
Nothing happens.

Reproduces How Often
Always

Versions
Voice iOS SDK
5.5.1

Xcode
12.3.0

iOS Version
14.2.0

iOS Device
iPhone 7 Plus

**Comment by salman-pixarsart** [comment] 2021-01-07 15:15
How can I debug or be sure that I'm receiving a VoIP notification when the app is in a closed state.
In my case sometimes I do receive a call in a closed state.

**Comment by bobiechen-twilio** [comment] 2021-01-07 17:20
Hi @salman-pixarsart 

To ensure the app can handle the VoIP notifications properly in the background or when the app was terminated previously, the iOS app must have PkPushRegistry object initialized in the frontmost component, usually in the AppDelegate (name might vary) where application lifecycle events are handled. You can follow the quickstart sample or the [migration guide](https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md) and apply necessary updates.

**Comment by salman-pixarsart** [comment] 2021-01-11 18:14
@bobiechen-twilio Thanks for the response. I'll give it a try and will update here.

**Comment by bobiechen-twilio** [comment] 2021-01-15 21:57
Hi @salman-pixarsart,

I am hoping that you managed to resolve the issue and the app is working well now.
Closing the issue for now but please feel free to reach out to us in the future.

Best,
-bobie

**Closed by bobiechen-twilio** 2021-01-15 21:57 UTC

**Comment by salman-pixarsart** [comment] 2021-01-16 11:19
Yes, you can close for now since I'm not a native IOS Developer so I'm still trying to figure out how can I achieve that in react-native.

**Comment by rakefetWorkiz** [comment] 2021-03-09 11:39
@bobiechen-twilio 
I was having the same issue with twilio voice and react native, 
and I moved my push registry logic to the app delegate like you have in the quick start app, 
but this didn't help, and I am still not able to see voip pushes if the app is killed and the screen is locked. 

the call will start ringing only after I load the app ( even tho it was already canceled on the other side) 
and if a long time passed from the moment the call was suppose to ring - until i open the app again - it will also create a crash (probably because voip push wasn't reported to CallKit)

any idea what could be the cause and how to fix?

**Comment by rakefetWorkiz** [comment] 2021-03-14 17:51
@bobiechen-twilio 

So eventually I got this working by turning my class into a singleton.

I basically changed my main delegates class into singleton that can live alone outside the ViewController scope, and is the endpoint to all voice actions. 

This way, I don't need to worry about my react native bridge having to use the same class - I just call getInstance, and get the same one, and in AppDelegate again I user getInstance to handle incoming VoIP notifications. 

So I got this in my AppDelegate (extension) now: 

```
@objc extension AppDelegate: PKPushRegistryDelegate {


  public func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {

    MyVoice.getInstance().credentialsUpdated(credentials: pushCredentials)
  }

  public func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
    MyVoice.getInstance().credentialsInvalidated();
  }

  public func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType) {
    VoiceHelper.addLog("app delegate incoming push")
    MyVoice.getInstance().incomingPushReceived(payload: payload)
  }

  public func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
    VoiceHelper.addLog("app delegate incoming push with completion")
    MyVoice.getInstance().incomingPushReceived(payload: payload, completion: completion)
  }

}
```

And I have another small class that contains the bridge between button actions in the app - and the Voice logic. 

And I have one big MyVoice class, that contains all the logic you have inside the ViewController. 
The MyVoice class became a Singleton like this: 

```
class MyVoice: NSObject {

  static var instance : MyVoice?;

  // MARK: Class Properties
  .... all properties... 
  
  override init() {

    let configuration = CXProviderConfiguration(localizedName: "Workiz")
    configuration.maximumCallGroups = 1
    configuration.maximumCallsPerCallGroup = 1
    if let callKitIcon = UIImage(named: "CallKitIcon") {
      configuration.iconTemplateImageData = callKitIcon.pngData()
    }

    callKitProvider = CXProvider(configuration: configuration)

    super.init()

    TwilioVoiceSDK.audioDevice = audioDevice
    callKitProvider.setDelegate(self, queue: nil)

    MyVoice.instance = self;
  }

  deinit {
    VoiceHelper.addLog("MyVoice : deinit")
    // CallKit has an odd API contract where the developer must call invalidate or the CXProvider is leaked.
    callKitProvider.invalidate()
  }

  static func getInstance() -> MyVoice {
    if let _instance = instance {
      return _instance;
    }
    instance = MyVoice();
    return instance!;
  }

 
... THE REST IS IN EXTENSIONS ...
}
```


I believe this can help a lot of people that want to support voice actions beyond just one voice controller. and of course - for people using a wrapper for other languages like react native :)

**Comment by bobiechen-twilio** [comment] 2021-03-15 22:04
@raffaele-abramini thanks for graciously sharing your findings and code snippet with us and I am sure React Native developers will benefit from the this.

**Comment by bobiechen-twilio** [comment] 2021-03-16 16:04
@rakefetWorkiz Thanks for graciously sharing your findings and code snippet with us and I am sure React Native developers will benefit from the this.
