### ISSUE TITLE
Unable to connect using mobile network

### ISSUE THREAD

**Issue by savchenkosoft** [twilio/voice-quickstart-ios#132] opened 2018-05-21 10:20 UTC
### Description

I'm trying to call from one device connected to mobile network (LTE/3G) to another device connected to LTE/3G. I'm unable to do it because connection failed with "Connection timeout" error OR connection is established, but no voice hear. If I use wifi there are any problems, works as expected. Encountering this issue also on Android device with same symptoms.

### Steps to Reproduce

1. Launch application on two phones connected to mobile network LTE or 3G
2. Start call
3. Call failed or no voice

#### Expected Behavior

Successfull call with voice using mobile network

#### Actual Behavior

Unsuccessfull call/ call with no voice using mobile network

#### Reproduces How Often

100% when using mobile network.
90% - failed call with "Connection timeout". 10% - success call with no voice

#### Logs

1. Failed call with "Connection timeout" error

```
pushRegistry:didReceiveIncomingPushWithPayload:forType:
callInviteReceived:
2018-05-21 12:56:33.045409+0300 app-ios[2004:710880] [DEBUG Twilio] init Twilio user agent.
WARNING: no real random source present!
2018-05-21 12:56:33.083515+0300 app-ios[2004:710880] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/16000/1 -> priority: 255
2018-05-21 12:56:33.083700+0300 app-ios[2004:710880] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/8000/1 -> priority: 254
2018-05-21 12:56:33.084063+0300 app-ios[2004:710880] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/32000/1 -> priority: 0
2018-05-21 12:56:33.084348+0300 app-ios[2004:710880] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMU/8000/1 -> priority: 128
2018-05-21 12:56:33.084565+0300 app-ios[2004:710880] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMA/8000/1 -> priority: 0
2018-05-21 12:56:33.085801+0300 app-ios[2004:710880] [INFO Twilio] recreateMainTransport, Found valid IPv4 address: 10.79.188.196
2018-05-21 12:56:33.125666+0300 app-ios[2004:710880] [INFO TVOCall] Inside publishConnectionEvent:, event type: incoming
2018-05-21 12:56:33.126528+0300 app-ios[2004:710880] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending incoming event
2018-05-21 12:56:33.127050+0300 app-ios[2004:710880] [DEBUG TwilioVoice] Inside addActiveCall:, adding call <TVOCall: 0x1c0125780>
2018-05-21 12:56:33.127172+0300 app-ios[2004:710880] [DEBUG TVOReachability] Reachability Flag Status: WR t------ networkStatusForFlags
2018-05-21 12:56:33.127249+0300 app-ios[2004:710880] [DEBUG TVOCommandHandler] Inside postCommand:, received command of type TVOAcceptCallCommand
2018-05-21 12:56:33.127374+0300 app-ios[2004:710880] [INFO TVOCall] Inside publishConnectionEvent:, event type: accepted-by-local
2018-05-21 12:56:33.128079+0300 app-ios[2004:710880] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending accepted-by-local event
2018-05-21 12:56:33.128472018-05-21 12:56:33.128977+0300 app-ios[2004:721957] [VERBOSE Twilio] Inside constructUri: Registration URL: sip:None@chunderm.gll.twilio.com;transport=tls
2018-05-21 12:56:33.150133+0300 app-ios[2004:721957] [INFO TVOAcceptCallCommand] Call URI: sip:None@chunderm.gll.twilio.com;transport=tls
2018-05-21 12:56:33.150331+0300 app-ios[2004:721957] [VERBOSE TVOCallImpl] Inside makeCall, record permission was granted
3+0300 app-ios[2004:710880] [DEBUG TVOCallInvite] dealloc.
2018-05-21 12:56:33.154589+0300 app-ios[2004:721957] [DEBUG Twilio] Inside on_call_state(), call: 0x1c0125780, internal state: 1
2018-05-21 12:56:33.154700+0300 app-ios[2004:721957] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CALLING
2018-05-21 12:56:33.154779+0300 app-ios[2004:721957] [VERBOSE TVOCall] handlePJSIPInviteStateCalling. Error: (null)
2018-05-21 12:56:33.154847+0300 app-ios[2004:721957] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-05-21 12:57:00.005238+0300 app-ios[2004:710880] Status bar could not find cached time string image. Rendering in-process.
2018-05-21 12:57:05.155600+0300 app-ios[2004:722241] [VERBOSE Twilio] on_call_tsx_state(), state: 6, status_code: 408: Request Timeout
2018-05-21 12:57:05.156376+0300 app-ios[2004:722241] [DEBUG Twilio] Inside on_call_state(), call: 0x1c0125780, internal state: 2
2018-05-21 12:57:05.156680+0300 app-ios[2004:722241] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_DISCONNECTED, internal state: 2, last_status: 408
2018-05-21 12:57:05.157636+0300 app-ios[2004:722241] [VERBOSE TVOCall] handlePJSIPInviteStateDisconnected. Error: Error Domain=com.twilio.voice.error Code=31003 "Connection timeout." UserInfo={NSLocalizedDescription=Connection timeout., NSLocalizedFailureReason=The server could not produce a response within a suitable amount of time}
Call failed to connect: Connection timeout.
2018-05-21 12:57:05.160928+0300 app-ios[2004:722144] [DEBUG TwilioVoice] Inside removeFromActiveCalls:, remove call <TVOCall: 0x1c0125780> from active calls
2018-05-21 12:57:05.167121+0300 app-ios[2004:722144] [DEBUG Twilio] dealloc Twilio.
dequeueIfNeedsAndInterruptCall
2018-05-21 12:57:05.847531+0300 app-ios[2004:710880] [INFO TVOCall] Inside publishConnectionEvent:, event type: error
2018-05-21 12:57:05.848600+0300 app-ios[2004:710880] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending error event
2018-05-21 12:57:05.849099+0300 app-ios[2004:710880] [DEBUG TVOCall] dealloc.
```
2. Call connection established, but no voice

```
pushRegistry:didReceiveIncomingPushWithPayload:forType:
callInviteReceived:
2018-05-21 13:10:03.530097+0300 app-ios[2024:728331] [DEBUG Twilio] init Twilio user agent.
WARNING: no real random source present!
2018-05-21 13:10:03.626696+0300 app-ios[2024:728331] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/16000/1 -> priority: 255
2018-05-21 13:10:03.626766+0300 app-ios[2024:728331] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/8000/1 -> priority: 254
2018-05-21 13:10:03.626822+0300 app-ios[2024:728331] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/32000/1 -> priority: 0
2018-05-21 13:10:03.626857+0300 app-ios[2024:728331] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMU/8000/1 -> priority: 128
2018-05-21 13:10:03.626892+0300 app-ios[2024:728331] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMA/8000/1 -> priority: 0
2018-05-21 13:10:03.627222+0300 app-ios[2024:728331] [INFO Twilio] recreateMainTransport, Found valid IPv4 address: 10.104.135.7
2018-05-21 13:10:03.627646+0300 app-ios[2024:728331] [DEBUG TVOConstants] X-Twilio-Client string: {"p":"ios","v":"2.0.4","mobile":{"arch":"arm64","product":"iPhone","name":"iPhone9,3","v":"11.3.1"}}, inside TVOConstants clientString
2018-05-21 13:10:03.629239+0300 app-ios[2024:728331] [INFO TVOCall] Inside publishConnectionEvent:, event type: incoming
2018-05-21 13:10:03.630824+0300 app-ios[2024:728331] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending incoming event
2018-05-21 13:10:03.631219+0300 app-ios[2024:728331] [DEBUG TwilioVoice] Inside addActiveCall:, adding call <TVOCall: 0x1c413eb40>
2018-05-21 13:10:03.631285+0300 app-ios[2024:728331] [DEBUG TVOReachability] Reachability Flag Status: WR t------ networkStatusForFlags
2018-05-21 13:10:03.631345+0300 app-ios[2024:728331] [DEBUG TVOCommandHandler] Inside postCommand:, received command of type TVOAcceptCallCommand
2018-05-21 13:10:03.631423+0300 app-ios[2024:728331] [INFO TVOCall] Inside publishConnectionEvent:, event type: accepted-by-local
2018-05-21 13:10:03.631736+0300 app-ios[2024:728331] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending accepted-by-local event
2018-05-21 13:10:03.631942+0300 app-ios[2024:728331] [DEBUG TVOCallInvite] dealloc.
2018-05-21 13:10:03.632161+0300 app-ios[2024:729012] [VERBOSE Twilio] Inside constructUri: Registration URL: sip:None@chunderm.gll.twilio.com;transport=tls
2018-05-21 13:10:03.632187+0300 app-ios[2024:729012] [INFO TVOAcceptCallCommand] Call URI: sip:None@chunderm.gll.twilio.com;transport=tls
2018-05-21 13:10:03.632618+0300 app-ios[2024:729012] [VERBOSE TVOCallImpl] Inside makeCall, record permission was granted
2018-05-21 13:10:03.635138+0300 app-ios[2024:729012] [DEBUG Twilio] Inside on_call_state(), call: 0x1c413eb40, internal state: 1
2018-05-21 13:10:03.635189+0300 app-ios[2024:729012] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CALLING
2018-05-21 13:10:03.635219+0300 app-ios[2024:729012] [VERBOSE TVOCall] handlePJSIPInviteStateCalling. Error: (null)
2018-05-21 13:10:03.635250+0300 app-ios[2024:729012] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-05-21 13:10:04.597878+0300 app-ios[2024:729010] [DEBUG Twilio] on_transport_state(): 0
2018-05-21 13:10:04.598348+0300 app-ios[2024:729010] [DEBUG Twilio] ------>Transport connected: 0x70e2228, inside transportConnected:
2018-05-21 13:10:04.809206+0300 app-ios[2024:729010] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-05-21 13:10:04.810729+0300 app-ios[2024:729010] [DEBUG Twilio] In on_call_redirected, call_id: 0, target: 0x106a28808, pjsip_event: 0x16b640658
2018-05-21 13:10:04.812490+0300 app-ios[2024:729010] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-05-21 13:10:04.812938+0300 app-ios[2024:729010] [VERBOSE Twilio] on_call_tsx_state(), state: 4, status_code: 302: Moved Temporarily
2018-05-21 13:10:04.814136+0300 app-ios[2024:729010] [VERBOSE Twilio] on_call_tsx_state(), state: 6, status_code: 302: Moved Temporarily
2018-05-21 13:10:04.815077+0300 app-ios[2024:729010] [DEBUG Twilio] ------>Destroying transport: 0x1070e2228, inside releaseTransport
2018-05-21 13:10:05.649541+0300 app-ios[2024:729010] [DEBUG Twilio] on_transport_state(): 0
2018-05-21 13:10:05.649882+0300 app-ios[2024:729010] [DEBUG Twilio] ------>Transport connected: 0x70f5028, inside transportConnected:
2018-05-21 13:10:05.897549+0300 app-ios[2024:729010] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
2018-05-21 13:10:05.898457+0300 app-ios[2024:729010] [DEBUG Twilio] Inside on_call_state(), call: 0x1c413eb40, internal state: 2
2018-05-21 13:10:05.898717+0300 app-ios[2024:729010] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CONNECTING
2018-05-21 13:10:05.898974+0300 app-ios[2024:729010] [VERBOSE TVOCall] handlePJSIPInviteStateConnecting. Error: (null)
pushRegistry:didReceiveIncomingPushWithPayload:forType:
2018-05-21 13:10:06.022027+0300 app-ios[2024:728331] [VERBOSE TwilioVoice] Inside createCallInviteCanceledNotification:, no matching call invite to cancel.
2018-05-21 13:10:06.527865+0300 app-ios[2024:729013] [VERBOSE Twilio] Active ports before pjsua_conf_connect(): 2
2018-05-21 13:10:06.527865+0300 app-ios[2024:729010] [DEBUG Twilio] Inside on_call_state(), call: 0x1c413eb40, internal state: 4
2018-05-21 13:10:06.527991+0300 app-ios[2024:729010] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CONFIRMED
2018-05-21 13:10:06.528018+0300 app-ios[2024:729010] [VERBOSE TVOCall] handlePJSIPInviteStateConfirmed. Error: (null)
2018-05-21 13:10:06.528315+0300 app-ios[2024:729010] [VERBOSE Twilio] on_call_tsx_state(), state: 6, status_code: 200: OK
2018-05-21 13:10:06.528487+0300 app-ios[2024:729013] [VERBOSE Twilio] Active ports after pjsua_conf_connect(): 2
2018-05-21 13:10:06.528598+0300 app-ios[2024:728331] callDidConnect
2018-05-21 13:10:06.528932+0300 app-ios[2024:729010] [VERBOSE Twilio] Inside on_rx_response(): received INVITE response, rewriting contact
stopWaitCallTimer
2018-05-21 13:10:06.531884+0300 app-ios[2024:729013] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CA5de90881ea1920abfa19ec4bc97cea62;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-05-21T13:10:06.531+03:00";
    "timestamp_ms" = 1526897406531;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
...
2018-05-21 13:10:30.559626+0300 app-ios[2024:729012] [VERBOSE TVORTCMonitor] Inside statsToSample:, call quality sample: {
    "audio_level_in" = 1;
    "audio_level_out" = 0;
    "call_sid" = CA5de90881ea1920abfa19ec4bc97cea62;
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2018-05-21T13:10:30.556+03:00";
    "timestamp_ms" = 1526897430556;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 192320;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 1202;
}
2018-05-21 13:10:30.802493+0300 app-ios[2024:729010] [VERBOSE Twilio] on_call_tsx_state(), state: 4, status_code: 200: OK
2018-05-21 13:10:30.802858+0300 app-ios[2024:729010] [VERBOSE Twilio] on_call_tsx_state(), state: 4, status_code: 200: OK
2018-05-21 13:10:30.803141+0300 app-ios[2024:729010] [DEBUG Twilio] Inside on_call_state(), call: 0x1c413eb40, internal state: 5
2018-05-21 13:10:30.803392+0300 app-ios[2024:729010] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_DISCONNECTED, internal state: 5, last_status: 200
2018-05-21 13:10:30.803728+0300 app-ios[2024:729010] [VERBOSE TVOCall] handlePJSIPInviteStateDisconnected. Error: (null)
2018-05-21 13:10:30.803994+0300 app-ios[2024:729010] [INFO TVOCall] Inside publishConnectionEvent:, event type: disconnected-by-remote
2018-05-21 13:10:30.814111+0300 app-ios[2024:729010] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending disconnected-by-remote event
Call didDisconnectWithError
Call disconnected
2018-05-21 13:10:30.820906+0300 app-ios[2024:728881] [DEBUG TwilioVoice] Inside removeFromActiveCalls:, remove call <TVOCall: 0x1c413eb40> from active calls
2018-05-21 13:10:30.821104+0300 app-ios[2024:728881] [DEBUG Twilio] dealloc Twilio.
2018-05-21 13:10:30.821274+0300 app-ios[2024:728881] [DEBUG Twilio] ------>Destroying transport: 0x1070f5028, inside releaseAllTransports
2018-05-21 13:10:30.821497+0300 app-ios[2024:728881] [DEBUG Twilio] on_transport_state(): 2
```

#### Voice iOS SDK

TwilioVoice (2.0.4) via CocoaPods

#### Xcode

Version 9.3 (9E145)

#### iOS Version

11.3.1, 10.3.3, Android 7.0

#### iOS Device

iPhone 7, iPhone X, iPhone SE, Samsung Galaxy S8

**Comment by bchen-twilio** [comment] 2018-05-22 06:43
Hi @savchenkosoft 

Thanks for providing SDK logs. I did check them:
1. The `408 timeout` error code usually indicates the connectivity is poor and unfortunately will cause the SDK to fail call setup.
2. I didn't see any obvious error message in the second log and I am assuming the app does not use the CallKit framework integration. Does this happen 10/10 and have you tried the same steps with the Swift quickstart?

-bobie

**Comment by savchenkosoft** [comment] 2018-05-22 07:30
@bchen-twilio thanks for response.
1. I can't say that my LTE and even 3G connections is some kind of poor. I'm able to watch high quality video content, use VoIP calls in other applications. Also my colleague from the way another country have the same symptoms. One more thing - there's no difference between using real LTE/3G connection and Network Conditioner. In both cases result is the same.
2. Yes, I don't use CallKit because of project requirements. I implement all the steps with the Swift quickstart, it happens 10/10 when I have my WiFi switched off, any iOS 10+ device.

My other colleague is using same backend as me, but for Android device. He also can't speak using mobile network. Can it be the same reason?

**Comment by bchen-twilio** [comment] 2018-05-23 20:48
Hi @savchenkosoft 

Sorry for my delay of responding back to you.
The Voice SDK, both Android and iOS, first performs some DNS resolution tasks to determine the address of the Twilio Voice Service hosts then it can establish the signaling connection. More than one factors could have had affected the connection. If we can narrow this down to only cellular, it would be great if you can increase the logging level to `.verbose` and we can find out what is causing the no-audio issue.

Also it would be great if you can report the issue with Android debugging logs in the [Android quickstart repo](https://github.com/twilio/voice-quickstart-android).

Thanks
-bobie

**Comment by savchenkosoft** [comment] 2018-05-24 07:17
@bchen-twilio This is already `.vebose` logging :)

**Comment by bchen-twilio** [comment] 2018-05-24 17:10
Hi @savchenkosoft 

I've passed the Call SID to the Voice Service backend experts and asked them to further investigate if there is any anomaly during the call signaling establishment. There is one more thing I'd like to ask for your help - would it be possible for you to enable Voice Trace of the account from the [Programmable Voice Settings page](https://www.twilio.com/console/voice/settings)? This will make our backend experts to see more insights of the calls.

Thanks!
-bobie

**Comment by savchenkosoft** [comment] 2018-05-25 07:03
@bchen-twilio Ok, I creat new ticket to turn Voice Trace on. Thank you, will wait for results

**Comment by bchen-twilio** [comment] 2018-05-25 16:52
Thanks @savchenkosoft 👍

**Comment by piyushtank** [comment] 2020-03-10 01:29
@MasterSAone Apologies for the delay. Are you still running into the problem? 
Our latest SDK is more stable and has more features in it, I recommend using it.

**Comment by piyushtank** [comment] 2020-03-11 01:16
@MasterSAone Closing the ticket assuming the problem is resolved at your end. Feel to reopen the ticket if you are still running into the issue or have questions.

**Closed by piyushtank** 2020-03-11 01:16 UTC
