### ISSUE TITLE
Getting Twilio Connection error 503

### ISSUE THREAD

**Issue by newMobileStar** [twilio/voice-quickstart-ios#108] opened 2018-02-07 20:01 UTC
I am trying to build a video and voice calling app using the latest TwilioVoice and TwilioVideo SDK.
It was working fine, but from a few hours ago, I am getting 503 error when make a call and connect to a video room.
Accesstokens are retrieved from my server, and it gives right token.
Why I get this 503 error from a few hours ago ? is there a missing part on my side or Twilio server side error ?

**Comment by idelgado** [comment] 2018-02-07 20:08
@newMobileStar which server endpoint is resulting in a 503?

**Comment by newMobileStar** [comment] 2018-02-07 20:15
Thank you for your response.

I am getting 503 connection error from Twilio server.
In detail, when I make a call, I get the right accesstoken from my server, but making a call is failed.
I logged the error in CallFailToConnecError delegate function. It says connection error (503).
I think that it's twilio server side problem.
or any missing part on my side ?

**Comment by kbagchiGWC** [comment] 2018-02-07 20:42
@newMobileStar 
Can you please collects logs with log level set to `TVOLogLevelVerbose`?
We may need to look at your access token details.  Open a support ticket with the log file and the access token used when you received `503`.

Please be mindful not to share your access token here or in any public forum.

**Comment by kbagchiGWC** [comment] 2018-02-07 20:43
@newMobileStar You can open a ticket by using this link : https://support.twilio.com/hc/en-us/requests/new .

**Comment by newMobileStar** [comment] 2018-02-07 20:51
Is the 503 error related with a country limit ?

**Comment by kbagchiGWC** [comment] 2018-02-07 20:54
I am not sure what you mean by "country limit". Are you trying in a region/country that never worked before?

**Comment by newMobileStar** [comment] 2018-02-07 21:00
I am in Finland, and My partner is in USA. I sent the same app build to my partner. On his side, the app works well, but on my side, I get the error.
If I post my accesstoken here, can you know the reason of the error ?

**Comment by kbagchiGWC** [comment] 2018-02-07 21:07
@newMobileStar Please DO NOT share your accessToken here. Can you please open a support ticket using https://support.twilio.com/hc/en-us/requests/new link? Share all the details there. If this is a region specific issue, one of our support engineers should be able to help you. 

Share the ticket number here so that I can follow up.

**Comment by newMobileStar** [comment] 2018-02-07 22:34
I got this ticket number : #1249222

**Comment by kbagchiGWC** [comment] 2018-02-07 22:38
@newMobileStar You forgot to add details about your location where it does not work, your partner location where it works. Please add logs and your access token in the ticket  #1249222 as well.

**Comment by newMobileStar** [comment] 2018-02-07 22:45
I saw this article:
https://support.twilio.com/hc/en-us/articles/115015195668-Troubleshooting-Call-Delivery-Issues-to-Programmable-Voice-SDK

It says that "For iOS, verify that your Sandbox push credential is not being used in Production, and vice versa". 
I think that this can help me.
But I want to confirm.
As a developer, I am using the same push credential in sandbox mode.
But my partner check the app in production mode. so he will use the push credential in production mode.
My questions is:
A same voip token and client identity can be used in both mode (sandbox and production) together ?

**Comment by kbagchiGWC** [comment] 2018-02-07 23:10
As the doc suggested, the same token can’t be used. There should be an independent device token for sandbox vs production.

**Comment by newMobileStar** [comment] 2018-02-07 23:24
Ok, thank you for your support

**Comment by newMobileStar** [comment] 2018-02-08 05:29
Dear Twilio team.
I didn't still fixed this issue.

when I make a call, AccessToken is right, but I face this error in callFailToConnectWithError function (TVOCall Delegate)
"PJSIP_INV_STATE_DISCONNECTED, internal state: 2, last_status: 503"
[TVO log.zip](https://github.com/twilio/voice-quickstart-swift/files/1705802/TVO.log.zip)

**Comment by kbagchiGWC** [comment] 2018-02-09 16:57
@newMobileStar 

The log you provided in the ticket did not include details I was looking for. Can you please add the following two lines to your code and collect logs again?
```
 [[TwilioVoice sharedInstance] setLogLevel:TVOLogLevelVerbose];
 [[TwilioVoice sharedInstance] setModule:TVOLogModulePJSIP logLevel:TVOLogLevelVerbose];
```
Thanks.

**Comment by newMobileStar** [comment] 2018-02-09 19:40
Ok, I will

**Comment by mahyarr** [comment] 2018-03-01 19:55
Is the Connection error (503) accessToken related? Some of my users are reporting this issue and unfortunately Im not able to collect verbose logs as the app is already out the wild.

**Comment by bchen-twilio** [comment] 2018-03-01 20:21
Hi @mahyarr 

The `503 Connection Error` typically means that the SDK is unable to reach to the Twilio service with the network connection on the device. Sometimes it's temporary and should work after attempting to connect again, but if the users keep getting the same `503` error then we will need to take a deeper look at the environment of the end users device.

**Comment by mahyarr** [comment] 2018-03-01 20:22
Ok thanks, Ill try collecting more info from users who are having this issue

**Comment by piyushtank** [comment] 2020-03-10 01:18
@mahyarr Hoping the issue is resolved. I am closing the old ticket but feel free to reopen if you run into the same issue or have any questions.

**Closed by piyushtank** 2020-03-10 01:18 UTC
Labels: question
