### ISSUE TITLE
Fails to register for Twilio push notifications (http status: 400. Unexpected registration response)

### ISSUE THREAD

**Issue by enaluz** [twilio/voice-quickstart-ios#297] opened 2019-11-12 16:44 UTC
#### Problem
Application fails to register for VoIP push notifications after receiving JWT from server.

#### Other Details
- I'm building this application using React Native
- Forked [this](https://github.com/hoxfon/react-native-twilio-programmable-voice) library and applied some small changes to the iOS side. This might not be relevant, but just thought I should share. The main change I made was related to the iOS 13 migration for 2.0.0 -> 2.1.0 outlined [here](https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md#migrating-from-twilio-voice-20-to-21) 
- I've confirmed that the server code is correct because calls work as expected on Android, which tells me the problem must be iOS-specific, not related to the access token/JWT generation
- JWT is valid (and works for Android). The schema looks like this: 
```
{
  "jti": "x",
  "grants": {
    "identity": "14151234567", // a phone number
    "voice": {
      "incoming": {
        "allow": true
      },
      "outgoing": {
        "application_sid": "x"
      },
      "push_credential_sid": "x"
    }
  },
  "iat": x,
  "exp": x,
  "iss": "x",
  "sub": "x"
}
```
- JWT is definitely getting to `register:deviceToken:completion:`
- I've created a VoIP Push Credential on Twilio using the VoIP Services Certificate I generated in the Apple Developer dashboard
- I've ensured the Twilio VoIP Push Credential is a sandbox SID
- I'm also creating a Debug, not a Release build on my physical device.

### Steps to Reproduce
Unfortunately is too long for anyone to realistically reproduce this problem. Though I'm happy to answer questions related to this if it would help!

#### Code
I can share more if needed, but this is how I'm registering for push notifications.

```
- (void)pushRegistry:(PKPushRegistry *)registry didUpdatePushCredentials:(PKPushCredentials *)credentials forType:(NSString *)type {
  if ([type isEqualToString:PKPushTypeVoIP]) {
    const unsigned *tokenBytes = [credentials.token bytes];
    self.deviceTokenString = [NSString stringWithFormat:@"<%08x %08x %08x %08x %08x %08x %08x %08x>", 
    ntohl(tokenBytes[0]), ntohl(tokenBytes[1]), ntohl(tokenBytes[2]),
    ntohl(tokenBytes[3]), ntohl(tokenBytes[4]), ntohl(tokenBytes[5]),
    ntohl(tokenBytes[6]), ntohl(tokenBytes[7])];

    self.deviceTokenString = [credentials.token description];
    NSString *accessToken = [self fetchAccessToken];

   [TwilioVoice registerWithAccessToken:accessToken
      deviceToken:self.deviceTokenString
      completion:^(NSError *error) {
        if (error) {
          NSLog(@"An error occurred while registering: %@", [error localizedDescription]);
          NSMutableDictionary *params = [[NSMutableDictionary alloc] init];
          [params setObject:[error localizedDescription] forKey:@"err"];

          [self sendEventWithName:@"deviceNotReady" body:params];
        } else {
          NSLog(@"Successfully registered for VoIP push notifications.");
          [self sendEventWithName:@"deviceReady" body:nil];
        }
      }
    ];
  }
}

```

#### Expected Behavior
Call hits iOS application and opens CallKit UI when a call is received.

#### Actual Behavior
Application fails to register for Twilio push notifications and cannot receive calls.

#### Reproduces How Often
Always fails.

#### Logs

```
[ERROR TwilioVoice] Inside register:deviceToken:completion:, failed to register for Twilio push notifications. Error:Http status: 400. Unexpected registration response.
```
I omitted the rest of the logs that didn't seem important to keep it brief and readable, but happy to share more if needed.

#### Voice iOS SDK
Version 2.1.0 installed via CocoaPods

#### Xcode
Xcode version 11.2

#### iOS Version
Build target in Xcode is iOS 10 but running 13.2

#### iOS Device
iPhone XS (physical device, not simulator)

**Comment by piyushtank** [comment] 2020-03-11 00:45
@enaluz Hoping the issue is resolved. Closing the ticket as it is opened for long without any activity. Feel free to reopen if you run into the issue or have questions.

**Closed by piyushtank** 2020-03-11 00:45 UTC
