### ISSUE TITLE
PKPushRegisteryDelegate methods never called in swift 3

### ISSUE THREAD

**Issue by ankitpansuria** [twilio/voice-quickstart-ios#286] opened 2019-12-12 09:31 UTC
### Description

I downloaded voice-quickstart-swift repository and followed all steps provided to get the app running. When app launches PKPushRegisteryDelegate method is not invoked in swift 3. The same code works fine with swift 4

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

4.1.0 via CocoaPods

#### Xcode

10.1

#### iOS Version

12.4

#### iOS Device

iPhone 6, 6s

**Comment by bchen-twilio** [comment] 2019-12-12 17:44
Hi @ankitpansuria 

While I cannot try Swift 3 compiler on Xcode 11, I remember when we updated the quickstart to use Swift 4 we needed to change the method signatures of PKPushRegisteryDelegate. Did you see any warnings when building with Swift 3?

**Comment by ankitpansuria** [comment] 2019-12-16 12:21
Build succeeds without any errors or warning. But delegate methods are not invoked when app is opened.

**Comment by bchen-twilio** [comment] 2019-12-16 17:23
Hi @ankitpansuria 

Couple of questions:
- Did you receive the `pushRegistry:didUpdatePushCredentials:forType:` callback with the device token when you initialize the PkPushRegistry instance?
- The delegate methods of the `PKPushRegistryDelegate` protocol were updated in the Swift 4 version iOS SDK like the updates in [this PR](https://github.com/twilio/voice-quickstart-swift/pull/259/files). This was a breaking change from Swift 3 to Swift 4 so I am asking if the method signature works for you in your Swift 3 environment.

**Comment by piyushtank** [comment] 2020-03-11 01:00
@ankitpansuria Closing the ticket assuming the problem is resolved at your end. Feel to reopen the ticket if you are still running into the issue or have questions.

**Closed by piyushtank** 2020-03-11 01:00 UTC
