### ISSUE TITLE
Will my application receive incoming call if it is in kiosk mode?

### ISSUE THREAD

**Issue by Unnikrishnanvenad** [twilio/voice-quickstart-ios#294] opened 2020-01-08 17:13 UTC
Hi,

My ios application receive incoming call when it is not in kiosk mode. If it is in kiosk it doesn't recieve the incoming call . Any possibility to figure out the exact case? Please help me to resolve this?

Thanks,

**Comment by piyushtank** [comment] 2020-01-08 19:55
Hi @Unnikrishnanvenad 

Can you confirm if you are receiving any other push notifications on your app in Kiosk mode? I haven't tried Kiosk mode yet but my best guess is either its configuration issue in the app OR prohibited by Apple. Also, if you provide steps on how to reproduce the problem OR share a branch, I will be happy to try it out.

Best,
Piyush

**Comment by ceaglest** [comment] 2020-01-09 19:44
Hi @Unnikrishnanvenad,

Are you referring to [guided access mode](https://support.apple.com/en-ca/HT202612)?

I used to use it on iPads that were always on, running a single app. They didn't use push because the app had a persistent connection. I don't see any options specific to notifications, but yes it would be great if you could confirm if you are able to receive other push notifications when this mode is activated.

Best,
Chris

**Comment by piyushtank** [comment] 2020-01-09 21:17
Hi @Unnikrishnanvenad 

If the device can't get a push notification in kiosk mode, then the other option is to put the call in a queue and signal it to the device in kiosk mode using your own persistent connection.

https://www.twilio.com/docs/voice/queue-calls

Let me know if you have any questions,

Best,
Piyush

**Comment by Unnikrishnanvenad** [comment] 2020-01-10 11:24
Hi @piyushtank 

Step to reproduce
1. First device get super wised using apple configurator (https://support.jamfnow.com/s/article/207704656-Supervising-iOS-Devices-with-Apple-Configurator-2-5-or-Later)

2. connect a super wised device  to apple configurator and select and right-click ->  choose advanced option -> and start with single app mode->  choose twilio app which receive incoming call notification 

3. When device is in single app mode then make a call to the device

See what happens

Thanks,

**Comment by Unnikrishnanvenad** [comment] 2020-01-10 11:34
Hi,

device - iPhone 7, 
os - iOS 13.3

When i tested my app in single app kiosk. I got a crash "Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback."

After the device get crashed . My twilio application above ios 13 not receive any call notification

Please help me to find out any possibility!

Thanks,

**Comment by piyushtank** [comment] 2020-03-11 01:06
@Unnikrishnanvenad iOS kills app with "Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback." when the app receives push notification but it does n't report incoming push to CallKit. Can you make sure your app reports incoming calls to PushKit ? see[ migration guide](https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md).

**Comment by bchen-twilio** [comment] 2020-04-29 18:12
Closing ticket since there has been activities for a while.

@Unnikrishnanvenad Please feel free to reopen the issue or reach out to us if you run into any problem using the Voice SDK.

Thanks,
bobie

**Closed by bchen-twilio** 2020-04-29 18:12 UTC

**Comment by SaugataBhandari** [comment] 2021-07-12 09:13
Hi , I am having the same issue. I am not able to receive incoming calls in ios kiosk mode. I am using TwilioVoice 5.1.1 objective c sdk and ios version is 14.4.1.
