### ISSUE TITLE
Getting 52131 Invalid APNS credentials

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-ios#142] opened 2018-06-08 04:28 UTC
Hello Twilio Support,

For the last few days I'm getting the error `52131 - Invalid APNS credentials` on my Twilio Console dashboard. For this reason I'm facing issues with incoming call. 

Here are the steps I followed to create the new push credentials:

1. Created a new VoIP certificate on Apple Developer site.
2. Exported the certificate and the private key as .p12.
3. Extracted the certificate and private key from .p12 file using the openssl command.
4. Opened cert.pem in TextEdit, copied the content, and pasted in the Certificate field in Twilio Push credentials page.
5. Opened key.pem in TextEdit, copied the content, and pasted in the Certificate field in Twilio Push credentials page.
6. Twilio shown that Push Credentials have been successfully created.
7. Copied the Push Credentials SID and provided the same at the back end.

Now when I try to make an incoming call I get the `52131 Invalid APNS credentials` error on Twilio Console Dashboard

Please let me know what I am missing.

Thanks

**Comment by benSmith1981** [comment] 2018-07-12 01:02
Dear BChen, I also have the same issue but with Programmable. 

When I test my sandbox APN certifcates the push notifications work perfectly. However when I create APN PUSH notifcations and upload these to my Twilio account (I use separate Twilio API credentials for the sandbox and for the Push, and I created a separate Twilio Programmable chat for development and one for production). I have followed all the instructions many many times. Doing exactly what you said but whenever I use my APN PUSH Services Certificate, with the Programmable chat function I have I always get the error message: 52131 - Invalid APNs credentials...I am totally confused as they are not invalid, infact I regenerated my APN Push Credentials and relinked them to the APP ID I use for the App I am creating.

I read in one your replies to a similar issue you said something about not having the Sandbox and PUSH SERVICES APN certificate in the same App ID? Or not using the same CertificateSigningRequest to generate the Sandbox and PUSH? My SID for my release programmable chat that is getting the erros is: IS0f9c58cdde5441feb7eb520aa828df94 

Just to clarify, the push notifications work perfectly on my development project SID: IS5c984ff02c934f2699520f429f2e3a3d
I use a Sandbox APN certificate, and selected the Sandbox tick box

In the development version, where I am using a specific APN Apple Push Services Certificate, for a unique APP ID does not work and I get the 52131 error. I did not tick use for sending to Sandbox credential. I followed all the instructions perfectly for exporting the certificate keys. I also use separate API Keys and a separate Programmable chat. I get registration of bindings but no notifications as the certificate is invalid, which I cannot see why it is? This is the bug https://www.twilio.com/console/runtime/debugger/NOf2857a6c1db54e27984dd8fa9ff5100f

**Comment by rochapablo** [comment] 2018-12-24 11:03
https://stackoverflow.com/questions/53888958/twilio-incoming-calls-not-working-for-ios

**Comment by bchen-twilio** [comment] 2019-04-02 01:08
Hi @ojhakapil 
Is the push notification issue resolved by the suggestion?

Hi @benSmith1981 
The Programmable Voice SDK requires an Apple VoIP Service certificate for incoming call notification delivery. This is different from the regular APNS certificate used by the Twilio Notify service. You can follow [the guide](https://github.com/twilio/voice-quickstart-swift#bullet7) to set up the VoIP cert and integrate with your Programmable Voice SDK application.

Hi @rochapablo 
There might be some old bindings created with the certificate that was previously used. Please contact [Twilio Support](https://support.twilio.com/hc/en-us) and create a ticket. You can then provide your account credentials in the support ticket and we can reach out to the Twilio Notify team to see if they can help with the cleanup.

Thanks
-bobie

**Comment by benSmith1981** [comment] 2019-04-03 14:56
Hi Bobie,
Actually the notificaitons have again stopped working...again i don;t know
what i did wrong. I cannot see the new bindings being created for users
which is annoyhing, altho I can def see channels being created and messages
passing through them. Just the binding doesn't work. I removed all the old
bindings... if you can help that would be great... will create a ticket too!
Ben

**Comment by bchen-twilio** [comment] 2019-04-03 17:11
Hi @benSmith1981 

Are you experiencing binding problem with Programmable Chat? I am afraid that I am not the expert to provide assistance but you can go to the [twilio-chat-ios](https://github.com/twilio/twilio-chat-ios/issues) repo and create a ticket.

Thanks
-bobie

**Comment by benSmith1981** [comment] 2019-04-03 17:53
Ok Done, You know I have been speaking to you abou tthis issue for over a
year now. It is most furstrating...Just seems to break then fix it self...i
really wish it didn't happen as I can spend many days trying to figure out
whats wrong!

**Comment by benSmith1981** [comment] 2019-04-05 11:01
Hi Bobbie,
I think the issue might be because I am trying to re-register the same
device with Twilio after removing the previous binding and account. I just
tested notifications on production with a new iPad and the iPad receives
the notifiations...Are bindings created depending on the Device ID? To get
a chat token i have to send the deviceID:

        *let* urlString = "\(tokenURL)?identity=\(uniqueID)&device=\(
deviceId)"


What could be the problem? Do I need to send a different device ID to
re-register a binding for notificaitons? Or will twilio fix this?


One more question, how do I localise notification messages to the receiving
device?


Ben

**Comment by bchen-twilio** [comment] 2019-04-05 16:33
Hi @benSmith1981 

The Twilio Notify team should be the expert here to answer your question but I am assuming together the unique identity and unique device ID should create a unique binding under your Twilio Account SID so you can later send a push notification by targeting the device ID and identity.

When you said there is a problem after being able to receive notification with the new devices, what exactly was the unexpected result were you experiencing?

For message localization, please consult with the Notify team, but AFAIK the application should be able to send any message as long as it conforms to the character set supported by the system. The iOS application can have the localization implementation and present the notification message based on the localization mapping to different languages.

-bobie

**Comment by piyushtank** [comment] 2020-03-11 01:16
@benSmith1981  Closing the ticket assuming the problem is resolved. Feel to reopen the ticket if you are still running into the issue or have questions.

**Closed by piyushtank** 2020-03-11 01:16 UTC
