### ISSUE TITLE
Call gets disconnected after few seconds when iOS app state is terminated

### ISSUE THREAD

**Issue by prabhatVinsol** [twilio/voice-quickstart-ios#433] opened 2021-01-28 10:32 UTC

**Comment by bobiechen-twilio** [comment] 2021-01-28 16:53
Hi @prabhatVinsol 

Could you please provide more information regard how the app is terminated? It would also help if you can describe the expected behavior in your application.

The SDK objects will be destroyed when the app is being terminated and any active calls won't be ended properly, but you can consider it disconnected since the SDK (or the app) is gone.

If you believe the call was disconnected unexpectedly, please provide Twilio Call SIDs so we can check them for you.

**Comment by KodyKendall** [comment] 2021-01-29 15:51
I'm not 100% sure if my issue is related to this or not, because poster didn't leave more details, but it sounds like it could be the same thing I'm experiencing where the calls never make it to my iOS app and no push notification is sent out.

**Comment by prabhatVinsol** [comment] 2021-02-01 04:54
When the app is terminated and gets the push for the call. It passes to the call kit and the user gets the call.
What is happening right now is I am trying to open the call screen in the app after passing this push to the call kit.
There it gets terminated and hence call disconnected. It was working fine for me in iOS13. But now it is crashing.
@bobiechen-twilio could you please suggest the best way to handle this scenario.

**Comment by bobiechen-twilio** [comment] 2021-02-02 18:18
Thanks for the update @prabhatVinsol. Is it possible to provide more information about the crash such as stacktrace or SDK logs?

**Comment by prabhatVinsol** [comment] 2021-02-04 13:25
@bobiechen-twilio Please provide best practice for the following scenario:
1. App is in the terminated state
2. Push received for call and passed to call kit
3. Device starts ringing
4. Receive the call from System UI
5. App launches and the call gets disconnected

Second scenario when the app is locked:
After step 4
5. User start conversation using system UI
6. There is a button with an app icon showing on the system UI call
7. Click on the button
8. app launches and the call gets disconnected


Please help me out here for handling this scenario. @bobiechen-twilio

**Comment by bobiechen-twilio** [comment] 2021-02-04 17:28
Hi @prabhatVinsol 

Any SDK logs or debugging messages showing why the call is disconnected? Also does this happen in the quickstart?

**Comment by bobiechen-twilio** [comment] 2021-02-17 18:15
@prabhatVinsol Have you managed to get debugging messages, crash logs, or SDK logs when this happened?

**Comment by prabhatVinsol** [comment] 2021-02-17 18:23
@bobiechen-twilio Since the app is in the terminated state, not getting a crash log.
Now, One situation I need to take care which is:
- Gets call in the terminated state
- User able to pick the call with the system UI
- System UI has the option to launch the app
- On clicking of this icon launches the app but the call gets disconnected

Need help to manage this scenario/use-case.
Please provide best practices to tackle this problem.

**Comment by bobiechen-twilio** [comment] 2021-02-17 18:38
Thanks for the update @prabhatVinsol.

In case the app crashed in this situation, you should be able to retrieve crash logs from Xcode device/simulator view by plugging the device to your working machine.

You can also debug this scenario by enabling "Wait for executable to launch": https://stackoverflow.com/questions/53930603/how-to-debug-an-app-after-it-is-terminated-and-then-reopened-in-xcode

Another options is to redirect the log messages to a file so you can view offline without having the device connected to Xcode debugger: http://azizuysal.com/redirecting-nslog-output-to-a-file-on-demand-for-iphone-debugging/

Back to problem: it definitely seems like the call was disconnected unexpectedly, either something went wrong the app was reporting the incoming call to CallKit or the SDK returned an error via the callback while trying to accept and connect the call. Please check the callbacks for any errors.

**Comment by bobiechen-twilio** [comment] 2021-03-03 21:02
Hi @prabhatVinsol 
I am hoping no news is good news and you probably managed to find and resolve the issue. Closing ticket for now but please feel free to reach out.

**Closed by bobiechen-twilio** 2021-03-03 21:02 UTC
