### ISSUE TITLE
Call immediately disconnected after connecting 

### ISSUE THREAD

**Issue by TechnoBrigadeInfotech** [twilio/voice-quickstart-ios#309] opened 2020-02-18 12:12 UTC
### Description

We are trying to make a call. Call initiate successfully but it gets disconnected immediately after connection
 
### Steps to Reproduce

1. Call from User1 to User 2

#### Expected Behavior

Calling functionality should work properly

#### Actual Behavior

Calling is not working

#### Reproduces How Often

100%

#### Logs

```
// Log output when the issue occurs
```
2020-02-18 17:33:13.433753+0530 SalesBuddy[762:132824] StartCallAction transaction request successful
2020-02-18 17:33:13.440088+0530 SalesBuddy[762:132180] provider:performStartCallAction:
2020-02-18 17:33:14.548253+0530 SalesBuddy[762:132180] provider:didActivateAudioSession:
2020-02-18 17:33:17.226625+0530 SalesBuddy[762:132180] callDidConnect:
2020-02-18 17:33:17.291355+0530 SalesBuddy[762:132180] AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580 "(null)"
2020-02-18 17:33:17.329433+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Call connected: <TVOCall: 0x2808b3c00>
2020-02-18 17:33:17.329590+0530 SalesBuddy[762:132180] INFO:Twilio:[Platform](0x100c85800): Inside publishConnectionEvent:, event name: connected
2020-02-18 17:33:17.329926+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Inside publisherConnectionEvent:, sending connected event
2020-02-18 17:33:17.330243+0530 SalesBuddy[762:132180] DEBUG:Twilio:[Platform](0x100c85800): Received ICE event.
	Group: ice-connection-state
	Name: completed
2020-02-18 17:33:17.330961+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Received call quality metrics: 
{
    "audio_codec" = "";
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" = CAc4a3b13c9f580d64f82694854b055a12;
    direction = OUTGOING;
    jitter = 0;
    mos = "4.433328";
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    "sdk_version" = "5.1.1";
    timestamp = "2020-02-18T17:33:17.331Z";
    "timestamp_ms" = 1582027397225;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
2020-02-18 17:33:18.235141+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Received call quality metrics: 
{
    "audio_codec" = opus;
    "audio_level_in" = 331;
    "audio_level_out" = 13050;
    "call_sid" = CAc4a3b13c9f580d64f82694854b055a12;
    direction = OUTGOING;
    jitter = 0;
    mos = "4.433328";
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 45;
    rtt = 0;
    "sdk_version" = "5.1.1";
    timestamp = "2020-02-18T17:33:18.234Z";
    "timestamp_ms" = 1582027398231;
    "total_bytes_received" = 6393;
    "total_bytes_sent" = 4368;
    "total_packets_lost" = 0;
    "total_packets_received" = 45;
    "total_packets_sent" = 50;
}
2020-02-18 17:33:19.240732+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Received call quality metrics: 
{
    "audio_codec" = opus;
    "audio_level_in" = 323;
    "audio_level_out" = 245;
    "call_sid" = CAc4a3b13c9f580d64f82694854b055a12;
    direction = OUTGOING;
    jitter = 12;
    mos = "4.42275";
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 51;
    rtt = 0;
    "sdk_version" = "5.1.1";
    timestamp = "2020-02-18T17:33:19.239Z";
    "timestamp_ms" = 1582027399236;
    "total_bytes_received" = 12745;
    "total_bytes_sent" = 8713;
    "total_packets_lost" = 0;
    "total_packets_received" = 96;
    "total_packets_sent" = 100;
}
2020-02-18 17:33:20.245089+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Received call quality metrics: 
{
    "audio_codec" = opus;
    "audio_level_in" = 435;
    "audio_level_out" = 12025;
    "call_sid" = CAc4a3b13c9f580d64f82694854b055a12;
    direction = OUTGOING;
    jitter = 12;
    mos = "4.42275";
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 50;
    rtt = 0;
    "sdk_version" = "5.1.1";
    timestamp = "2020-02-18T17:33:20.244Z";
    "timestamp_ms" = 1582027400241;
    "total_bytes_received" = 19887;
    "total_bytes_sent" = 13180;
    "total_packets_lost" = 0;
    "total_packets_received" = 146;
    "total_packets_sent" = 151;
}
2020-02-18 17:33:21.249624+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Received call quality metrics: 
{
    "audio_codec" = opus;
    "audio_level_in" = 370;
    "audio_level_out" = 15868;
    "call_sid" = CAc4a3b13c9f580d64f82694854b055a12;
    direction = OUTGOING;
    jitter = 12;
    mos = "4.42275";
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 50;
    rtt = 0;
    "sdk_version" = "5.1.1";
    timestamp = "2020-02-18T17:33:21.248Z";
    "timestamp_ms" = 1582027401246;
    "total_bytes_received" = 27008;
    "total_bytes_sent" = 17575;
    "total_packets_lost" = 0;
    "total_packets_received" = 196;
    "total_packets_sent" = 201;
}
2020-02-18 17:33:22.254497+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Received call quality metrics: 
{
    "audio_codec" = opus;
    "audio_level_in" = 460;
    "audio_level_out" = 6517;
    "call_sid" = CAc4a3b13c9f580d64f82694854b055a12;
    direction = OUTGOING;
    jitter = 12;
    mos = "4.42275";
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 50;
    rtt = 0;
    "sdk_version" = "5.1.1";
    timestamp = "2020-02-18T17:33:22.253Z";
    "timestamp_ms" = 1582027402250;
    "total_bytes_received" = 34049;
    "total_bytes_sent" = 21992;
    "total_packets_lost" = 0;
    "total_packets_received" = 246;
    "total_packets_sent" = 251;
}
2020-02-18 17:33:23.260483+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Received call quality metrics: 
{
    "audio_codec" = opus;
    "audio_level_in" = 558;
    "audio_level_out" = 14627;
    "call_sid" = CAc4a3b13c9f580d64f82694854b055a12;
    direction = OUTGOING;
    jitter = 15;
    mos = "4.340662";
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 50;
    rtt = 127;
    "sdk_version" = "5.1.1";
    timestamp = "2020-02-18T17:33:23.259Z";
    "timestamp_ms" = 1582027403256;
    "total_bytes_received" = 40579;
    "total_bytes_sent" = 26415;
    "total_packets_lost" = 0;
    "total_packets_received" = 296;
    "total_packets_sent" = 301;
}
2020-02-18 17:33:23.953024+0530 SalesBuddy[762:132909] INFO:Twilio:[Signaling](0x16fff3000): RESIP::DUM: Got: SipReq:  BYE VoiceSDK@116.72.16.200:49139 tid=f253.730f8b6.0 cseq=1 BYE / 1 from(wire)
2020-02-18 17:33:23.953549+0530 SalesBuddy[762:132909] INFO:Twilio:[Signaling](0x16fff3000): RESIP::DUM: Handling in-dialog request: SipReq:  BYE VoiceSDK@116.72.16.200:49139 tid=f253.730f8b6.0 cseq=1 BYE / 1 from(wire)
2020-02-18 17:33:23.954043+0530 SalesBuddy[762:132909] INFO:Twilio:[Signaling](0x16fff3000): RESIP::DUM: Received SipReq:  BYE VoiceSDK@116.72.16.200:49139 tid=f253.730f8b6.0 cseq=1 BYE / 1 from(wire)
2020-02-18 17:33:23.954559+0530 SalesBuddy[762:132909] INFO:Twilio:[Signaling](0x16fff3000): RESIP::DUM: Transition InviteSession::Connected -> InviteSession::Terminated
2020-02-18 17:33:23.954999+0530 SalesBuddy[762:132909] DEBUG:Twilio:[Core](0x16fff3000): mapToSipCall handle id is 1
2020-02-18 17:33:23.955296+0530 SalesBuddy[762:132909] DEBUG:Twilio:[Core](0x16fff3000): casting handle id 1 to SipCall
2020-02-18 17:33:23.955578+0530 SalesBuddy[762:132909] DEBUG:Twilio:[Core](0x16fff3000): onTerminated: reason 4, this=0x10583fe00
2020-02-18 17:33:23.955863+0530 SalesBuddy[762:132909] DEBUG:Twilio:[Core](0x16fff3000): onTerminated
2020-02-18 17:33:23.956863+0530 SalesBuddy[762:132909] DEBUG:Twilio:[Core](0x16fff3000): ~SipCall(): 0x10583fe00
2020-02-18 17:33:23.958260+0530 SalesBuddy[762:132180] INFO:Twilio:[Platform](0x100c85800): Inside publishConnectionEvent:, event name: disconnected-by-remote
2020-02-18 17:33:23.958362+0530 SalesBuddy[762:132903] TRACE:Twilio:[Core](MediaFactoryImpl::signaling): stopDependents
2020-02-18 17:33:23.959761+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): Inside publisherConnectionEvent:, sending disconnected-by-remote event
2020-02-18 17:33:23.961948+0530 SalesBuddy[762:132903] DEBUG:Twilio:[Core](MediaFactoryImpl::signaling): OnIceConnectionChange
2020-02-18 17:33:23.962428+0530 SalesBuddy[762:132903] DEBUG:Twilio:[Core](MediaFactoryImpl::signaling): Call State: Disconnected ICE connection state: closed
2020-02-18 17:33:23.962870+0530 SalesBuddy[762:132180] DEBUG:Twilio:[Platform](0x100c85800): Received ICE event.
	Group: ice-connection-state
	Name: closed
2020-02-18 17:33:23.963207+0530 SalesBuddy[762:132903] DEBUG:Twilio:[Core](MediaFactoryImpl::signaling): OnSignalingChange
2020-02-18 17:33:23.963462+0530 SalesBuddy[762:132903] DEBUG:Twilio:[Core](MediaFactoryImpl::signaling): Signaling state: closed
2020-02-18 17:33:23.964679+0530 SalesBuddy[762:132180] DEBUG:Twilio:[Platform](0x100c85800): Received signaling-state event: closed
2020-02-18 17:33:24.108380+0530 SalesBuddy[762:132903] DEBUG:Twilio:[Core](MediaFactoryImpl::signaling): Shutting down DUM thread ...
2020-02-18 17:33:24.962519+0530 SalesBuddy[762:132903] DEBUG:Twilio:[Core](MediaFactoryImpl::signaling): Shutting down SIP stack thread ...
2020-02-18 17:33:24.963384+0530 SalesBuddy[762:132908] INFO:Twilio:[Signaling](0x16ff67000): RESIP::SIP: Shutting down stack thread
2020-02-18 17:33:24.964512+0530 SalesBuddy[762:132903] DEBUG:Twilio:[Core](MediaFactoryImpl::signaling): Deleting previously cached listen set ids
2020-02-18 17:33:24.964994+0530 SalesBuddy[762:132903] DEBUG:Twilio:[Core](MediaFactoryImpl::signaling): virtual twilio::voice::AsyncDnsResolver::~AsyncDnsResolver()
2020-02-18 17:33:24.965572+0530 SalesBuddy[762:132903] WARN:Twilio:[Signaling](MediaFactoryImpl::signaling): RESIP::TRANSACTION: On shutdown, there are Client TransactionStates remaining!
2020-02-18 17:33:24.968748+0530 SalesBuddy[762:132180] Call disconnected
2020-02-18 17:33:24.969929+0530 SalesBuddy[762:132180] DEBUG:Twilio:[Platform](0x100c85800): dealloc.
2020-02-18 17:33:24.970169+0530 SalesBuddy[762:132180] DEBUG:Twilio:[Core](0x100c85800): ~CallImpl
2020-02-18 17:33:24.972818+0530 SalesBuddy[762:132180] DEBUG:Twilio:[Core](0x100c85800): AppleReachability::~AppleReachability()
2020-02-18 17:33:24.976041+0530 SalesBuddy[762:132180] TRACE:Twilio:[Platform](0x100c85800): -[TVOEventReceiver dealloc]
2020-02-18 17:33:24.978243+0530 SalesBuddy[762:132180] DEBUG:Twilio:[Platform](0x100c85800): -[TVOMediaFactory dealloc]
2020-02-18 17:33:24.978439+0530 SalesBuddy[762:132180] INFO:Twilio:[Core](0x100c85800): ~AudioMediaFactoryImpl
2020-02-18 17:33:25.117317+0530 SalesBuddy[762:132180] provider:didDeactivateAudioSession:
2020-02-18 17:36:13.331110+0530 SalesBuddy[762:133537] [] tcp_input [C4.1:3] flags=[R] seq=2432990494, ack=0, win=0 state=CLOSE_WAIT rcv_nxt=2432990494, snd_una=893493219

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

Using TwilioVoice (5.1.1)

#### Xcode

Xcode 11.2.1

#### iOS Version

All versions above 10

#### iOS Device

On All Devices

**Comment by bchen-twilio** [comment] 2020-02-18 18:40
Hi @TechnoBrigadeInfotech 

Thanks for reaching out to us and providing the SDK log. I've checked the Call SID in the log and found that actually there is no client `bb` registered under this account at the moment, thus resulted in the call being disconnected immediately.

**Comment by TechnoBrigadeInfotech** [comment] 2020-02-19 04:31
Thank you
But how can I Register client under the account

**Comment by bchen-twilio** [comment] 2020-02-19 05:31
Hi @TechnoBrigadeInfotech 

Please use the TwilioVoice.registerWithAccessToken() method to register your mobile client. Here is the [API doc](https://twilio.github.io/twilio-voice-ios/docs/latest/Classes/TwilioVoice.html#//api/name/registerWithAccessToken:deviceToken:completion:). You can also find example in the quickstart. For more detailed instructions, please follow the [README](https://github.com/twilio/voice-quickstart-ios/blob/master/README.md).

**Comment by piyushtank** [comment] 2020-03-11 01:07
@TechnoBrigadeInfotech Closing the ticket assuming the problem is resolved at your end. Feel to reopen the ticket if you are still running into the issue or have questions.

**Closed by piyushtank** 2020-03-11 01:07 UTC
