### ISSUE TITLE
Twilio Incoming call

### ISSUE THREAD

**Issue by Unnikrishnanvenad** [twilio/voice-quickstart-ios#292] opened 2019-12-27 10:31 UTC
Hi

We implemented a Browser - device calling in my project. Currently i have done the process in a view controlller. Means twlio registration and call receive in a single view controller which run initially on app launch.
Here i just want to know that how could i done registration in appdelegate and call receive in another viewcontroller.

Can you please help me to find out how could i fix the scenario?

**Comment by bchen-twilio** [comment] 2019-12-30 02:48
Hi @Unnikrishnanvenad 

Thanks for reaching out.

The simplest way is to implement the `TVOCallDelegate` methods in the view-controller and pass the view-controller as the delegate when call the `TwilioVoice.handleNotification()` method upon receiving the incoming call notification in the app-delegate, where the `PkPushRegistryDelegate` methods are implemented.

-bobie

**Comment by piyushtank** [comment] 2020-03-11 01:09
@Unnikrishnanvenad Closing the ticket assuming the problem is resolved at your end. Feel to reopen the ticket if you are still running into the issue or have questions.

**Closed by piyushtank** 2020-03-11 01:09 UTC
Labels: help wanted
