### ISSUE TITLE
Callkit native UI for incoming call gets disappear once I click on answer button.

### ISSUE THREAD

**Issue by palsantosh** [twilio/voice-quickstart-ios#313] opened 2020-02-24 12:10 UTC
I am working on app in which I integrated twilio sdk for voice calling. For calling I configure callkit in my project. My issue is that whenever I trying to receive call, once I click on answer button callkit native UI screen get disappear and when I double click on home button that screen shown in stack in background.

**Comment by bchen-twilio** [comment] 2020-02-24 17:39
Hi @palsantosh 

Thanks for reaching out to us. This is the behavior designed by iOS. The UI will stay in the native Call UI if the call is answered when the device is locked, otherwise iOS will bring up the app.

-bobie

**Comment by piyushtank** [comment] 2020-03-11 01:10
@palsantosh Closing the ticket assuming the problem is resolved at your end. Feel to reopen the ticket if you are still running into the issue or have questions.

**Closed by piyushtank** 2020-03-11 01:10 UTC

**Comment by salman-pixarsart** [comment] 2021-01-19 13:32
What if we want to keep the native UI?

**Comment by bobiechen-twilio** [comment] 2021-01-19 17:32
@salman-pixarsart there doesn't seem any programmatic way to achieve this via CallKit API for now.
